
[polyglot.dotnet]
config    = ["{}.sln", "nuget.config", "Directory.Build.props"]
active    = []


[polyglot.dotnet-csharp]
suffixes  = [".cs", ".csproj"]
prefix    = "cs_"
active    = []

[polyglot.dotnet-fsharp]
suffixes  = [".fs", ".fsproj"]
prefix    = "fs_"
active    = []
